Repository prgrms-web-devcourse/Team-Moongsal-Travel.zip-FE, pull requests merged in 2023-02, with the labels that each got.

#14 [design] 검색 모달 디자인
  src/components/Header/Header.tsx
  src/components/SearchModal/SearchModal.tsx
  src/components/SearchModal/index.ts
  src/styles/CenterStyle.ts
  src/styles/GlobalStyle.tsx
  src/styles/MuiTheme.ts
Labels: 리뷰 요청, 코칭 요청, 프론트, design

#15 [design] 로그인 페이지 디자인
  src/components/Login/Local.tsx
  src/components/Login/Social.tsx
  src/components/Login/index.ts
  src/pages/auth/login.tsx
Labels: 리뷰 요청, 프론트, design

#17 [chore] experimental feature appDir 옵션 제거
  next.config.js
Labels: chore

#18 [feat] 검색 모달 구현
  src/components/Header/Header.tsx
  src/components/SearchModal/SearchModal.tsx
Labels: 리뷰 요청, 코칭 요청, 프론트, feat, design

#31 [test] Test API 테스트 코드 작성
  src/api/hooks/test.ts
  src/api/test/index.ts
  src/api/test/type.ts
  src/components/Test/Test.tsx
  src/pages/_app.tsx
Labels: test

#32 [feat] 회원가입 API 연동
  src/api/core/index.ts
  src/api/hooks/user.ts
  src/api/user/index.ts
  src/api/user/type.ts
  src/components/Register/Register.tsx
  src/components/Stepper/Stepper.tsx
  src/pages/auth/register.tsx
Labels: feat

#26 [design] 게시글 작성 페이지(여행 상세 정보)
  src/components/CreatePost/DatePicker.tsx
  src/components/CreatePost/Location.tsx
  src/components/CreatePost/PostBasic.tsx
  src/components/CreatePost/PostDetail.tsx
  src/components/CreatePost/StepperButton.tsx
  src/components/CreatePost/Transportation.tsx
  src/components/CreatePost/index.ts
  src/components/common/SubTitle.tsx
  src/components/common/Titlte.tsx
  src/components/common/index.ts
  src/pages/post/[id].tsx
Labels: 리뷰 요청, 프론트, design

#34 [design] 게시글 상세 페이지
  src/components/PostDetail/PostCategory.tsx
  src/components/PostDetail/PostContents.tsx
  src/components/PostDetail/PostInfo.tsx
  src/components/PostDetail/PostProfile.tsx
  src/components/PostDetail/index.ts
  src/components/common/SubTitle.tsx
  src/components/common/Titlte.tsx
  src/pages/post/detail/[id].tsx
Labels: 리뷰 요청, 프론트, design

#37 [feat] 회원가입 기능 구현
  .husky/pre-commit
  package.json
  src/api/user/index.ts
  src/api/user/type.ts
  src/components/Register/Register.tsx
  src/components/Register/VerifyByEmail.tsx
  src/components/Register/useGetUserForms.ts
  src/components/Stepper/Stepper.tsx
  src/pages/auth/register.tsx
  yarn.lock
Labels: 코칭 요청

#39 [feat] 위치 검색 자동완성 구현
  package.json
  src/components/SearchModal/AutoComplete.tsx
  src/components/SearchModal/PlacesAutocomplete.tsx
  src/components/SearchModal/SearchModal.tsx
  src/components/SearchModal/index.ts
  yarn.lock
Labels: 리뷰 요청, 프론트, feat, design, chore

#42 [feat] 게시글 작성 수정
  public/images/buttons/domestic.png
  public/images/buttons/foreign.png
  public/images/buttons/foreign.svg
  src/components/CreatePost/ComplexButton.tsx
  src/components/CreatePost/Location.tsx
  src/components/CreatePost/PostBasic.tsx
  src/constants/index.ts
  src/pages/post/[id].tsx
Labels: 리뷰 요청, 프론트, feat, design

#43 [feat] 로그인 기능 구현
  package.json
  src/api/hooks/user.ts
  src/api/user/index.ts
  src/components/Login/Local.tsx
  src/components/common/CommonInput.tsx
  src/components/common/index.ts
  src/types/auth.ts
  src/types/common.ts
Labels: 리뷰 요청, 프론트, feat

#46 [design] 게시글 피드 컴포넌트 디자인
  next.config.js
  src/components/Travelogue/FeedChip.tsx
  src/components/Travelogue/FeedContent.tsx
  src/components/Travelogue/FeedHeader.tsx
  src/components/Travelogue/FeedImage.tsx
  src/components/Travelogue/TravelogueFeed.tsx
  src/components/Travelogue/index.ts
  src/components/Travelogue/type.ts
  src/components/common/Row.tsx
  src/components/common/index.ts
  src/pages/index.tsx
Labels: 리뷰 요청, 프론트, design
