Repository prgrms-web-devcourse/Team-Moongsal-Travel.zip-FE, pull requests merged in 2023-03, with the labels that each got.

#48 [feat] 게시글 작성 페이지 구현
  src/api/core/index.ts
  src/api/post/createPost.ts
  src/components/CreatePost/DatePicker.tsx
  src/components/CreatePost/Location.tsx
  src/components/CreatePost/PostBasic.tsx
  src/components/CreatePost/PostComplete.tsx
  src/components/CreatePost/StepperButton.tsx
  src/components/common/FileInput.tsx
  src/components/common/index.ts
  src/hooks/usePostForm.ts
  src/pages/post/[id].tsx
  src/types/CreatePost.ts
  src/utils/helper.ts
Labels: 리뷰 요청, 프론트, feat

#50 [feat] 전체 게시글 피드 리스트 기능 1차 구현 (메인 페이지)
  src/api/hooks/travelogue.ts
  src/api/travelogue/index.ts
  src/components/CreatePost/StepperButton.tsx
  src/components/Travelogue/TravelogueFeed.tsx
  src/components/Travelogue/TravelogueList.tsx
  src/components/Travelogue/index.ts
  src/components/common/TemporaryButton.tsx
  src/components/common/index.ts
  src/pages/index.tsx
  src/styles/GlobalStyle.tsx
Labels: 리뷰 요청, 프론트, feat

#51 [refactor] 게시글 작성 페이지 구현
  src/api/core/index.ts
  src/api/post/createPost.ts
  src/components/CreatePost/StepperButton.tsx
  src/components/Header/Header.tsx
  src/components/common/AlertMessage.tsx
  src/components/common/index.ts
  src/hooks/usePostForm.ts
  src/pages/post/[id].tsx
  src/pages/post/first.tsx
Labels: 리뷰 요청, 프론트, feat, refactor

#54 [refactor] 닉네임 중복 확인 API 변경사항 반영
  src/api/user/index.ts
  src/components/Register/Register.tsx
  src/pages/auth/register.tsx
  src/types/auth.ts
Labels: refactor

#52 [feat] 게시글 작성 서브 페이지 구현
  src/api/hooks/post.ts
  src/api/post/createPost.ts
  src/api/post/index.ts
  src/components/CreatePost/DatePicker.tsx
  src/components/CreatePost/Location.tsx
  src/components/CreatePost/PostBasic.tsx
  src/components/CreatePost/PostDetail.tsx
  src/components/CreatePost/StepperButton.tsx
  src/components/CreatePost/Transportation.tsx
  src/components/common/FileInput.tsx
  src/hooks/usePostForm.ts
  src/hooks/useSubTravelogueForm.ts
  src/pages/post/first.tsx
  src/types/CreatePost.ts
  src/types/post.ts
Labels: feat

#61 [fix]: 게시글 목록 api 관련 데이터 타입 경로 변경으로 인한 경로 에러 수정
  src/components/Travelogue/FeedContent.tsx
  src/components/Travelogue/FeedHeader.tsx
  src/components/Travelogue/FeedImage.tsx
  src/components/Travelogue/TravelogueFeed.tsx
  src/types/travelogue.ts
Labels: 리뷰 요청, 프론트, fix

#63 [feat] S3 이미지 업로드 및 불러오기 구현
  next.config.js
  package.json
  src/api/hooks/post.ts
  src/api/post/index.ts
  src/api/user/index.ts
  src/components/CreatePost/DatePicker.tsx
  src/components/CreatePost/Location.tsx
  src/components/CreatePost/PostBasic.tsx
  src/components/CreatePost/PostDetail.tsx
  src/components/CreatePost/StepperButton.tsx
  src/components/common/FileInput.tsx
  src/constants/defaultFormValue.ts
  src/constants/index.ts
  src/hooks/useImageUpload.ts
  src/hooks/usePostForm.ts
  src/hooks/useSubTravelogueForm.ts
  src/pages/post/first.tsx
  src/types/post.ts
  yarn.lock
Labels: feat

#64 [refactor] 유효성 및 나라 자동완성
  src/api/post/index.ts
  src/components/CreatePost/ComplexButton.tsx
  src/components/CreatePost/DatePicker.tsx
  src/components/CreatePost/Location.tsx
  src/components/CreatePost/PostBasic.tsx
  src/components/CreatePost/StepperButton.tsx
  src/components/common/CountrySelect.tsx
  src/components/common/index.ts
  src/constants/index.ts
  src/hooks/useTravelogueForm.ts
  src/pages/post/first.tsx
  src/types/post.ts
Labels: 리뷰 요청, 프론트, feat, refactor

#67 [feat] 개인 추천 게시글 목록 무한 스크롤 구현
  .gitignore
  next.config.js
  package.json
  src/api/hooks/travelogue.ts
  src/api/travelogue/index.ts
  src/components/Main/PersonalFeedList.tsx
  src/components/Main/index.ts
  src/hooks/useIntersect.ts
  src/mocks/browser.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/travelogue.ts
  src/mocks/server.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  yarn.lock
Labels: 리뷰 요청, 프론트, feat, chore

#76 [design] 프로필 페이지 디자인
  src/components/Header/Header.tsx
  src/components/Profile/ContentLink.tsx
  src/components/Profile/Management.tsx
  src/components/Profile/index.ts
  src/components/common/CommonButton.tsx
  src/components/common/ProfileAvatar.tsx
  src/components/common/index.ts
  src/pages/profile/index.tsx
Labels: 리뷰 요청, design

#77 [feat] 서브 트래블로그 디테일 작업
  package.json
  src/api/post/index.ts
  src/components/CreatePost/Location.tsx
  src/components/CreatePost/PostDetail.tsx
  src/components/CreatePost/SubTravelogue.tsx
  src/components/CreatePost/index.ts
  src/components/Stepper/VerticalStepper.tsx
  src/components/Stepper/index.ts
  src/constants/defaultFormValue.ts
  src/hooks/useImageUpload.ts
  src/hooks/useSubTravelogueForm.ts
  src/pages/post/[id].tsx
  src/pages/post/first.tsx
  src/types/common.ts
  src/types/post.ts
  yarn.lock
Labels: feat

#75 [feat] subTravelogues 에디터 구현
  package.json
  src/components/CreatePost/PostDetail.tsx
  src/components/Editor/RichEditor.tsx
  src/components/Editor/editorModules.ts
  src/components/Editor/index.ts
  src/hooks/useImageUpload.ts
  src/styles/GlobalStyle.tsx
  yarn.lock
Labels: 리뷰 요청, 프론트, feat

#81 [feat] travelogue 키워드, 제목, 내용 검색 구현
  src/api/hooks/travelogue.ts
  src/api/travelogue/index.ts
  src/components/Header/Header.tsx
  src/components/SearchModal/PlacesAutocomplete.tsx
  src/components/SearchModal/SearchModal.tsx
  src/components/common/FilterButton.tsx
  src/components/common/index.ts
  src/pages/_app.tsx
  src/pages/post/travelogueList.tsx
  src/recoil/index.ts
  src/types/travelogue.ts
Labels: 리뷰 요청, 프론트, feat, design

#83 [feat] 서브 트래블로그 임시저장, 최종 발행 api 연동
  src/api/core/index.ts
  src/api/hooks/post.ts
  src/api/hooks/test.ts
  src/api/post/index.ts
  src/api/test/index.ts
  src/api/test/type.ts
  src/components/CreatePost/StepperButton.tsx
  src/components/CreatePost/SubTravelogue.tsx
  src/components/CreatePost/Transportation.tsx
  src/components/CreatePost/index.ts
  src/components/Register/Register.tsx
  src/components/Register/VerifyByEmail.tsx
  src/components/Stepper/VerticalStepper.tsx
  src/components/SubTravelogue/Location.tsx
  src/components/SubTravelogue/SubTravelogue.tsx
  src/components/SubTravelogue/Transportation.tsx
  src/components/SubTravelogue/VisitedRegion.tsx
  src/components/SubTravelogue/index.ts
  src/components/Test/Test.tsx
  src/hooks/useGetUserForms.ts
  src/pages/post/[id].tsx
  src/types/common.ts
  src/utils/helper.ts
  src/utils/storage.ts
Labels: feat, refactor

#85 [fix] 파일 경로 및 이름 변경에 따른 에러 수정
  src/components/CreatePost/PostDetail.tsx
  src/components/Editor/RichEditor.tsx
  src/components/SubTravelogue/SubTravelogue.tsx
  yarn.lock
Labels: fix

#82 [feat] axios interceptor을 이용한 Token 관리
  src/api/core/axiosInstance.ts
  src/api/core/helper.ts
  src/api/hooks/travelogue.ts
  src/api/travelogue/index.ts
Labels: 리뷰 요청, 프론트, feat

#88 [remove] 불필요한 의존성을 가진 msw 로직 제거
  package.json
  src/api/hooks/travelogue.ts
  src/api/travelogue/index.ts
  src/components/Main/PersonalFeedList.tsx
  src/mocks/browser.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/travelogue.ts
  src/mocks/server.ts
  src/pages/_app.tsx
  yarn.lock
Labels: 리뷰 요청, 프론트, remove, chore

#90 [feat] 트래블로그 상세 조회 API 연결
  src/api/hooks/travelogue.ts
  src/api/travelogue/index.ts
  src/pages/detail/index.tsx
  src/pages/post/detail/[id].tsx
  src/types/travelogue.ts
Labels: feat

#91 [fix] 게시글 피드 thumbnail image 데이터가 존재하지 않는 경우에 대한 static thumbnail image 적용
  public/images/default/no-image.jpg
  src/components/Travelogue/FeedImage.tsx
  src/constants/index.ts
Labels: 리뷰 요청, 프론트, fix

#92 [feat] msw api로 호출한 개인 추천 게시글 목록 데이터 실제 api로 변경
  src/api/core/axiosInstance.ts
  src/api/hooks/travelogue.ts
  src/api/travelogue/index.ts
  src/components/Main/PersonalFeedList.tsx
Labels: 리뷰 요청, 프론트, feat

#94 [feat] 서브 트래블로그 임시저장 리퀘스트 타입에 days 필드 추가
  src/components/SubTravelogue/SubTravelogue.tsx
  src/constants/defaultFormValue.ts
  src/types/post.ts
Labels: feat

#95 [design] 트래블로그 상세 페이지 구현
  package.json
  src/components/PostDetail/PostCategory.tsx
  src/components/PostDetail/PostContents.tsx
  src/components/PostDetail/PostInfo.tsx
  src/components/PostDetail/PostProfile.tsx
  src/components/PostDetail/index.ts
  src/components/SubTravelogue/Transportation.tsx
  src/components/TravelogueDetail/TravelInfo.tsx
  src/components/TravelogueDetail/TravelInfoItem.tsx
  src/components/TravelogueDetail/TravelogueContent.tsx
  src/components/TravelogueDetail/TravelogueDetail.tsx
  src/components/TravelogueDetail/TravelogueHeader.tsx
  src/components/TravelogueDetail/TravelogueInfo.tsx
  src/components/TravelogueDetail/VisitedRegionList.tsx
  src/components/TravelogueDetail/index.ts
  src/components/common/Spinner.tsx
  src/components/common/Titlte.tsx
  src/constants/index.ts
  src/pages/detail/index.tsx
  src/types/travelogue.ts
  yarn.lock
Labels: feat, design

#98 [feat] 검색 리스트 페이지 필터 구현
  src/api/hooks/travelogue.ts
  src/api/travelogue/index.ts
  src/components/common/FilterButton.tsx
  src/constants/defaultFormValue.ts
  src/hooks/useFilterForm.ts
  src/pages/post/travelogueList.tsx
  src/types/filter.ts
Labels: 코칭 요청, 프론트, feat, design

#100 [design] 로그인 유도 모달창 디자인
  src/components/common/CommonButton.tsx
  src/components/common/SigninLeadModal.tsx
  src/components/common/index.ts
  src/styles/CenterStyle.ts
  src/styles/GlobalStyle.tsx
Labels: 리뷰 요청, 프론트, design

#101 [design] 스크랩 페이지 디자인
  src/api/scrap/index.ts
  src/pages/scrap/index.tsx
Labels: 프론트, design

#103 [feat] 서브 트래블로그 작성 도중 수정 기능 구현
  src/api/hooks/post.ts
  src/api/post/index.ts
  src/components/Editor/RichEditor.tsx
  src/components/SubTravelogue/Location.tsx
  src/components/SubTravelogue/SubTravelogue.tsx
  src/components/SubTravelogue/Transportation.tsx
  src/components/SubTravelogue/VisitedRegion.tsx
Labels: feat

#104 [design] Navigation Bar 디자인하기
  src/components/GNB/GNB.tsx
  src/components/GNB/index.ts
  src/pages/_app.tsx
Labels: 리뷰 요청, 프론트, design

#106 [refactor] 회원가입 / 로그인 서버 API path 변경
  src/api/user/index.ts
Labels: refactor

#107 [feat] 글 작성시 첨부한 이미지 사이즈 조정
  package.json
  quill-image-resize.d.ts
  src/components/Editor/RichEditor.tsx
  src/components/Stepper/VerticalStepper.tsx
  src/components/SubTravelogue/SubTravelogue.tsx
  src/pages/post/[id].tsx
  src/pages/post/first.tsx
  src/utils/helper.ts
  yarn.lock
Labels: feat

#110 [feat] 서브 트래블로그 지역 자동 완성 구현
  src/components/SearchModal/AutoComplete.tsx
  src/components/SearchModal/AutoCompleteList.tsx
  src/components/SearchModal/PlacesAutocomplete.tsx
  src/components/SearchModal/SearchModal.tsx
  src/components/SearchModal/index.ts
  src/components/SubTravelogue/Location.tsx
  src/components/SubTravelogue/VisitedRegion.tsx
  src/hooks/useAutoComplete.ts
Labels: feat, refactor

#112 [feat] 프로필 관리 페이지 API 연결
  src/api/hooks/profile.ts
  src/api/profile/index.ts
  src/components/Profile/Management.tsx
  src/components/common/ProfileAvatar.tsx
  src/pages/profile/index.tsx
  src/types/profile.ts
Labels: 리뷰 요청, 프론트, feat

#116 [design] 프로필 수정 페이지 디자인
  src/components/Profile/EditDrawer.tsx
  src/components/Profile/EditForm.tsx
  src/components/Profile/MobileAppBarLayout.tsx
  src/components/Profile/index.ts
  src/components/SearchModal/SearchModal.tsx
  src/components/common/SigninLeadModal.tsx
  src/pages/profile/index.tsx
  src/styles/commonStyle.ts
Labels: 리뷰 요청, 프론트, design

#118 [feat] 트래블로그 수정 기능 구현
  src/api/hooks/post.ts
  src/api/post/index.ts
  src/components/CreatePost/DatePicker.tsx
  src/components/CreatePost/PostBasic.tsx
  src/components/TravelogueDetail/TravelogueHeader.tsx
  src/components/common/CountrySelect.tsx
  src/components/common/FileInput.tsx
  src/constants/index.ts
  src/hooks/useTravelogueForm.ts
  src/pages/post/[id].tsx
  src/pages/post/first.tsx
  src/types/post.ts
Labels: feat

#121 [design] Navigation Bar 최하단으로 위치 재구성
  src/components/GNB/GNB.tsx
  src/styles/MuiTheme.ts
Labels: 리뷰 요청, 프론트, design

#125 [refactor] 헤더 변경
  .stylelintrc
  src/components/Header/Header.tsx
  src/hooks/useAutoComplete.ts
  src/pages/_app.tsx
Labels: refactor

#127 [feat] Navigation Bar 라우터 연결
  src/components/GNB/GNB.tsx
  src/constants/path.ts
  src/types/common.ts
  src/utils/helper.ts
Labels: 리뷰 요청, 프론트, feat

#128 [design] global-font 변경
  src/components/Header/Header.tsx
  src/components/Login/Local.tsx
  src/components/Register/Register.tsx
  src/components/SubTravelogue/Location.tsx
  src/styles/GlobalStyle.tsx
  src/styles/MuiTheme.ts
Labels: design

#129 [feat] 서브 트래블로그 수정 기능 구현
  src/api/hooks/post.ts
  src/api/post/index.ts
  src/components/Stepper/VerticalStepper.tsx
  src/components/SubTravelogue/SubTravelogue.tsx
  src/components/TravelogueDetail/TravelogueContent.tsx
  src/components/TravelogueDetail/TravelogueDetail.tsx
  src/components/TravelogueDetail/TravelogueHeader.tsx
  src/components/TravelogueDetail/TravelogueInfo.tsx
  src/hooks/useHandleTraveloguePublish.ts
  src/pages/post/[id].tsx
  src/types/post.ts
  src/types/travelogue.ts
Labels: feat

#131 [fix] 에디터 첨부 이미지 최대 너비 제한
  package.json
  src/components/Editor/RichEditor.tsx
  yarn.lock
Labels: fix, chore

#134 [feat] 트래블로그 상세 조회시 작성자만 수정 버튼 보이기
  src/components/TravelogueDetail/TravelogueDetail.tsx
  src/components/TravelogueDetail/TravelogueHeader.tsx
  src/types/travelogue.ts
Labels: feat

#135 [feat] 로그인 유도 모달창 전역상태 관리
  src/api/core/helper.ts
  src/components/GNB/GNB.tsx
  src/components/Login/Local.tsx
  src/components/Travelogue/TravelogueFeed.tsx
  src/components/common/SigninLeadModal.tsx
  src/constants/index.ts
  src/hooks/useAuth.ts
  src/pages/_app.tsx
  src/recoil/index.ts
Labels: 리뷰 요청, 프론트, feat

#138 [design] 헤더 로고 변경
  public/images/index.ts
  public/images/logo.svg
  src/components/Header/Header.tsx
Labels: design

#140 [feat] 장소 스크랩 페이지 Navigation Bar에 추가
  src/components/GNB/GNB.tsx
  src/constants/path.ts
Labels: 프론트, feat

#142 [design] Main Page 디자인 재구성
  src/components/Main/PersonalFeedList.tsx
  src/components/Travelogue/FeedChip.tsx
  src/components/Travelogue/FeedContent.tsx
  src/components/Travelogue/PopularFeed/PopularFeed.tsx
  src/components/Travelogue/TravelogueFeed.tsx
Labels: 리뷰 요청, 프론트, design

#145 [fix] 잘못된 Travelogue Feed Data 수정
  src/api/travelogue/index.ts
  src/components/Travelogue/FeedContent.tsx
Labels: fix

#147 [design] 트래블로그 상세 조회 디자인 수정
  src/components/TravelogueDetail/TravelInfo.tsx
  src/components/TravelogueDetail/TravelogueContent.tsx
  src/components/TravelogueDetail/TravelogueHeader.tsx
  src/components/TravelogueDetail/TravelogueInfo.tsx
  src/components/TravelogueDetail/VisitedRegionList.tsx
Labels: design

#149 [design] 스크랩 문서 페이지 디자인 수정
  public/images/folder.svg
  public/images/index.ts
  public/images/scrapBg.svg
  src/components/GNB/GNB.tsx
  src/components/Header/Header.tsx
  src/pages/scrap/[docId].tsx
  src/pages/scrap/index.tsx
  src/styles/GlobalStyle.tsx
  src/styles/MobileLayout.tsx
  src/styles/MuiTheme.ts
Labels: design, refactor

#151 [design] 스크랩 상세 페이지 디자인 수정
  src/components/Header/Header.tsx
  src/pages/scrap/[docId].tsx
  src/pages/scrap/index.tsx
Labels: design

#154 [fix] 스크랩 추가 버그 수정
  src/components/Scrap/ScrapDialog.tsx
  src/components/TravelogueDetail/VisitedRegionList.tsx
Labels: fix

#152 [feat] 프로필 수정 기능 구현
  src/api/hooks/profile.ts
  src/components/Profile/EditDrawer.tsx
  src/components/Profile/EditForm.tsx
  src/components/Profile/Management.tsx
  src/components/Profile/MobileAppBarLayout.tsx
  src/constants/pattern.ts
  src/pages/profile/index.tsx
  src/recoil/index.ts
  src/types/profile.ts
Labels: 리뷰 요청, 프론트, feat

#157 summary
  src/api/hooks/travelogue.ts
  src/api/travelogue/index.ts
  src/components/Travelogue/PopularFeed/PopularFeed.tsx
  src/components/Travelogue/TravelogueList.tsx
  src/components/Travelogue/index.ts
  src/constants/path.ts
Labels: 리뷰 요청, 프론트, feat

#158 [design] 네브바 디자인 수정
  src/components/GNB/GNB.tsx
  src/constants/path.ts
Labels: design

#161 [refactor] 인기 게시글 목록 컴포넌트 재사용 가능한 공통 컴포넌트로 분리
  src/components/Main/PopularFeedList.tsx
  src/components/Main/index.ts
  src/components/Travelogue/PopularFeed/index.ts
  src/components/common/SwipeSlider.tsx
  src/pages/index.tsx
Labels: 프론트, refactor

#163 [design] 회원가입 페이지 디자인
  public/images/bigLogo.svg
  public/images/index.ts
  public/images/worldMap.svg
  src/components/Register/Register.tsx
  src/components/Register/VerifyByEmail.tsx
  src/components/Stepper/Stepper.tsx
  src/pages/auth/register.tsx
  src/styles/GlobalStyle.tsx
Labels: design

#165 [refactor] 에디터 수정
  src/components/Editor/editorModules.ts
  src/styles/GlobalStyle.tsx
Labels: design, refactor

#171 [design] 로그인 유도 모달 취소 버튼 hover 상태에서 불필요한 color 제거
  src/components/common/CommonButton.tsx
  src/components/common/SigninLeadModal.tsx
Labels: design

#172 [design] 메인 페이지 디자인 수정
  public/images/avatar.svg
  public/images/index.ts
  public/images/location.svg
  src/components/Main/PersonalFeedList.tsx
  src/components/Travelogue/FeedChip.tsx
  src/components/Travelogue/FeedContent.tsx
  src/components/Travelogue/FeedHeader.tsx
  src/components/Travelogue/TravelogueFeed.tsx
  src/components/common/SwipeSlider.tsx
Labels: design

#175 [fix] 게시글 작성자만 수정 버튼 보이게 수정
  src/components/TravelogueDetail/TravelogueContent.tsx
  src/components/TravelogueDetail/TravelogueDetail.tsx
  src/components/TravelogueDetail/VisitedRegionList.tsx
Labels: design

#178 [design] 디테일한 디자인 수정
  src/components/CreatePost/ComplexButton.tsx
  src/components/CreatePost/PostBasic.tsx
  src/components/Login/Local.tsx
  src/components/Main/PersonalFeedList.tsx
  src/components/Profile/Management.tsx
  src/components/Register/Register.tsx
  src/components/Register/VerifyByEmail.tsx
  src/components/SearchModal/AutoCompleteList.tsx
  src/components/Stepper/Stepper.tsx
  src/components/Stepper/VerticalStepper.tsx
  src/components/SubTravelogue/Location.tsx
  src/components/SubTravelogue/SubTravelogue.tsx
  src/components/SubTravelogue/Transportation.tsx
  src/components/SubTravelogue/VisitedRegion.tsx
  src/components/Travelogue/FeedChip.tsx
  src/components/Travelogue/FeedContent.tsx
  src/components/Travelogue/FeedHeader.tsx
  src/components/Travelogue/TravelogueFeed.tsx
  src/components/TravelogueDetail/TravelogueContent.tsx
  src/components/TravelogueDetail/TravelogueHeader.tsx
  src/components/TravelogueDetail/TravelogueInfo.tsx
  src/components/TravelogueDetail/VisitedRegionList.tsx
  src/components/common/AuthHeader.tsx
  src/components/common/FileInput.tsx
  src/components/common/FilterButton.tsx
  src/components/common/ProfileAvatar.tsx
  src/components/common/SubTitle.tsx
  src/components/common/Titlte.tsx
  src/components/common/UserProfile.tsx
  src/components/common/index.ts
  src/pages/post/[id].tsx
  src/pages/post/first.tsx
  src/pages/post/travelogueList.tsx
  src/pages/profile/index.tsx
  src/styles/GlobalStyle.tsx
  src/styles/commonStyle.ts
Labels: design

#180 [fix] 트래블로그 작성시 썸네일 선택창 안뜨는 오류 수정
  src/components/common/FileInput.tsx
Labels: fix

#182 design: 기본 이미지 사이즈 조정
  src/components/Profile/EditForm.tsx
  src/components/Profile/Management.tsx
  src/components/common/ProfileAvatar.tsx
Labels: fix, design

#186 [fix] Main 페이지 >> 인기 여행 일지 선택하면 항상 마지막 게시글로 이동하는 문제 해결
  src/components/Main/PopularFeedList.tsx
Labels: fix

#187 [design] 프로필 & 로그인 레이아웃 수정
  src/components/GNB/GNB.tsx
  src/components/Profile/EditDrawer.tsx
  src/components/Profile/TemporarySaveTravelogues.tsx
  src/components/Profile/WrittenByMeTravelogues.tsx
  src/components/common/AuthHeader.tsx
  src/pages/profile/index.tsx
  src/recoil/index.ts
Labels: design

#188 [design] 사용자가 작성/임시저장한 글이 없을 경우 처리
  public/images/addPost.svg
  public/images/index.ts
  public/images/tempPost.svg
  src/components/Profile/TemporarySaveTravelogues.tsx
  src/components/Profile/WrittenByMeTravelogues.tsx
  src/components/common/EmptyData.tsx
  src/components/common/SwipeSlider.tsx
  src/components/common/index.ts
  src/pages/profile/index.tsx
Labels: design

#189 [feat] Travelogue 목록 조회 API >> 조건에 따라 정렬
  src/api/hooks/travelogue.ts
  src/api/travelogue/index.ts
  src/components/Main/PersonalFeedList.tsx
  src/components/Main/PopularFeedList.tsx
  src/types/travelogue.ts
Labels: 리뷰 요청, 프론트, feat

#191 [design] 로그인 모달 디자인 수정
  public/images/index.ts
  public/images/logoBlue.svg
  src/components/SubTravelogue/VisitedRegion.tsx
  src/components/common/SigninLeadModal.tsx
  src/pages/profile/index.tsx
Labels: design

#193 [feat] 임시 저장 트래블로그 라우팅
  src/components/Profile/TemporarySaveTravelogues.tsx
  src/components/Travelogue/TravelogueFeed.tsx
  src/components/common/SwipeSlider.tsx
  src/pages/post/first.tsx
Labels: feat

#195 [fix] 이미지 관련 오류 수정
  src/components/Editor/RichEditor.tsx
  src/components/TravelogueDetail/TravelogueContent.tsx
  src/components/common/FileInput.tsx
  src/hooks/useImageUpload.ts
  src/pages/post/first.tsx
Labels: fix

#197 [chore] 여행 일지 띄어쓰기 수정
  src/components/Profile/WrittenByMeTravelogues.tsx
Labels: chore

#199 [design] 스크랩 디테일 리스트 크기조절
  src/pages/scrap/[docId].tsx
Labels: design

#201 [!hotfix] 임시 저장 글 클릭시 디테일 페이지로 이동하는 오류 수정
  src/components/Travelogue/TravelogueFeed.tsx
Labels: !hotfix

#206 axios instance 공통화
  src/api/auth/index.ts
  src/api/core/axiosInstance.ts
  src/api/core/index.ts
  src/api/main/index.ts
  src/api/member/index.ts
  src/api/scrap/index.ts
  src/api/search/index.ts
  src/api/travelogue/index.ts
Labels: refactor

#208 search api 수정
  src/api/search/index.ts
  src/hooks/query/search.ts
  src/pages/search/index.tsx
  src/types/search.ts
Labels: 리뷰 요청, refactor
